# Generated by Django 5.1.6 on 2025-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'News Data',
                'verbose_name_plural': 'News Data',
            },
        ),
        migrations.CreateModel(
            name='NewsSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
            },
        ),
    ]
