# Generated by Django 5.1.6 on 2025-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssources',
            name='status',
            field=models.BooleanField(db_default=False),
        ),
    ]
